name: Daily Job
on:
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run daily task
        run: python scripts/daily_task.py
      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p data
          git add -A
          git diff --staged --quiet && exit 0
          git commit -m "chore: daily update $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
